---
- name: Copia hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    mode: '0644'

- name: Deshabilita SELINUX
  lineinfile: dest=/etc/sysconfig/selinux regexp=^SELINUX= line=SELINUX=disabled

- name: Copia repo de Nodejs
  copy: src=node.repo dest=/etc/yum.repos.d/nodesource-el.repo

- name: Instala paquetes Base
  yum: name={{ item }} state=present
  with_items:
    - "{{ system_packages }}"

- name: Desactiva SELINUX
  selinux: state=disabled

- name: Desahbilita postfix
  service: name=postfix state=stopped enabled=no

- name: Desahbilita iptables
  service: name=firewalld state=stopped enabled=no

- name: Copia resolv.conf
  copy: src=resolv.conf dest=/etc/resolv.conf
